name: visit_flutter_sdk
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.4
  flutter_svg: ^2.2.1
  geolocator: ^10.1.1
  permission_handler: ^12.0.1
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.visit_flutter_sdk
        pluginClass: VisitFlutterSdkPlugin
      ios:
        pluginClass: VisitFlutterSdkPlugin


  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/disclaimer_icon.svg


  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish_regular.ttf
          style: normal
        - asset: assets/fonts/mulish_black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/mulish_semibold.ttf
          weight: 600
          style: normal
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
