# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  inappwebview_user_script = File.join(
    File.dirname(File.realpath(__FILE__)),
    '.symlinks',
    'plugins',
    'flutter_inappwebview',
    'ios',
    'Classes',
    'Types',
    'UserScript.swift'
  )
  if File.exist?(inappwebview_user_script)
    source = File.read(inappwebview_user_script)
    source.gsub!(
      /    @available\(iOS 14\.0, \*\)\n    lazy var contentWorld: WKContentWorld = WKContentWorld\.page/,
      <<~SWIFT
            private var contentWorldWrapper: Any?
            @available(iOS 14.0, *)
            var contentWorld: WKContentWorld {
              get {
                if let value = contentWorldWrapper as? WKContentWorld {
                  return value
                }
                return .page
              }
              set { contentWorldWrapper = newValue }
            }
      SWIFT
    )
    File.write(inappwebview_user_script, source)
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
